Homework 2
================
Elliot Kim
2024-10-02

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(ggplot2)
library(dplyr)
library(readxl)
library(tidyr)
```

## Problem 1

Import subway dataset and clean variables

``` r
nyc_subway = read.csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", na = c(".", "NA", "")) |> 
  janitor::clean_names() |>
  select(line:entry, vending, ada) |>
  mutate(entry = ifelse(entry =="YES", TRUE, FALSE))
```

The dataset above is called nyc_subway, which contains the following
variables about nyc subways: the lines, station names, station
latitude/longitude, routes(1-11), entrance type, entry, vending, and ADA
compliance. To clean this dataset, I first read the csv file and
standardized the column names. I then selected the variables listed
above using the select function. Finally, I modified the entry variable
by converting it from a character to a logical variable using the ifelse
function. This dataset has 1868 rows and 19 columns. The data is tidy as
each variable has a distinct column and each observation occupies a
distinct row.

Dataset questions and answers

``` r
distinct(nyc_subway, line, station_name) |>
  nrow()
```

    ## [1] 465

There are 465 distinct stations in this dataset.

``` r
filter(nyc_subway, ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 84

84 stations are ADA compliant.

``` r
filter(nyc_subway, vending == "NO", entry == "TRUE") |>
  summarise(proportion = n()/nrow(nyc_subway))
```

    ##   proportion
    ## 1  0.0369379

The proportion of station entrances/exits without vending allow
entrances is 3.69%

\##reformat data

``` r
nyc_subway2 = nyc_subway |>
  mutate(across(route1:route11, as.character)) |>
  pivot_longer(cols = route1:route11, names_to = "route_number", values_to = "route")

nyc_subway2 |>
  filter(route == "A") |>
  distinct(line, station_name) |>
  count()
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1    60

``` r
nyc_subway2 |>
  filter(route == "A", ada == TRUE) |>
  distinct(line, station_name) |>
  count()
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1    17

There are 60 dustubct stations that serve the A train. Of the stations
that serve the A train, 17 are ADA compliant.

## Problem 2

``` r
trash_wheel = read_excel("./data/202409 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel")
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
trash_wheel |>
  janitor::clean_names() |>
  select(dumpster:homes_powered) |>
  drop_na(dumpster)
```

    ## # A tibble: 651 × 14
    ##    dumpster month year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 641 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>
